# Configure GitHub pages builder.
theme: jekyll-theme-slate
# show_downloads: true
markdown: GFM
# kramdown:
#   input: GFM
#   gfm_quirks: [paragraph_end]
defaults:
  -
    scope:
      path: ""
    values:
      matrix.os: {{ matrix.os }}"
      github.workspace: "{{ github.workspace }}"
