name: BuildRc

on:
  workflow_dispatch:

jobs:
  buildrc:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Linux Venv
      run: |
        python -m venv ${{ github.workspace }}/env
        source ${{ github.workspace }}/env/bin/activate
        python -m pip --version
    - name: Install Pytest versions
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest>=5<6
        pytest --version
        python -m pip install --upgrade pytest>=6<7 --pre
        pytest --version
        python -m pip install --upgrade pytest>=6<7
        pytest --version
        python -m pip install --upgrade pytest>=7 --pre
        pytest --version
