name: BuildRc

on:
  workflow_dispatch:

jobs:
  buildrc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: pytest-dev/pytest
        ref: 7.0.0rc1
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Linux Venv
      run: |
        python -m venv ${{ github.workspace }}/env
        source ${{ github.workspace }}/env/bin/activate
        python -m pip --version
    - name: Install and build
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel twine
        python -m pip --version
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Upload dist
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        retention-days: 5
