name: BuildRc

on:
  workflow_dispatch:

jobs:
  buildrc:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Linux Venv
      run: |
        python -m venv ${{ github.workspace }}/env
        source ${{ github.workspace }}/env/bin/activate
        python -m pip --version
    - name: Install Pytest <6
      run: |
        python -m pip install --upgrade pip
        python -m pip install "pytest<6"
        pytest --version
    - name: Install Pytest <6 --pre
      run: |
        python -m pip install --upgrade "pytest<6" --pre
        pytest --version
    - name: Install Pytest <7
      run: |
        python -m pip install --upgrade "pytest<7"
        pytest --version
    - name: Install Pytest ==7 pre
      run: |
        python -m pip install --upgrade "pytest==7" --pre
        pytest --version
