name: Classifiers

on:
  workflow_dispatch:
  #push:
  #pull_request:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # todo- remove before running in phmdoctest repos
      with:
        repository: tmarktaylor/pytest-phmdoctest
        ref: develop
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
            
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install trove-classifiers
    - name: Classifiers
      run: |
        python tests/check_classifiers.py
