# Experimental demo.
name: Demo

on:
  workflow_dispatch:

jobs:
  windows-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      #- name: Install-matplotlib
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install matplotlib
      #    pip freeze
      #- name: Cities
      #  run: |
      #    python cities.py
      - name: Folding Demo
        run: >
          python -c '
          from pathlib import Path;
          glob = list(Path(".").glob("**.*"));
          print(glob)
          '
