name: Pytest Live Log Demo

on:
  workflow_dispatch:
# todo- restore
#  push:
#  pull_request:
#    branches: [master, develop]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # todo- for debug only, remove
      with:
        repository: tmarktaylor/phmdoctest
        ref: develop

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "pytest>=5"
        # todo- pip install -r requirements.txt
        pip install --use-feature=in-tree-build --no-deps "."
        pip freeze
    - name: Pytest Demo (Expect Annotations 1 error)
      continue-on-error: true
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        # Show setup, teardown, and doctests pytest run time order using
        # pytest Live Logs.
        # The terminal output should show the order:
        #     setup_module
        #     test_1
        #     test_2
        #     test_3
        #     teardown_module
        python -m pytest doc/livelog.py --log-cli-level=debug --color=yes

        # This is the same command plus the --doctest-modules option.
        # Note that the PASSED indication for session_00000 is printed
        # after setup_module log message.
        # The terminal output should show the order:
        #     setup_module
        #     session_00000
        #     session_00001
        #     session_00002
        #     teardown_module
        #     setup_module
        #     test_1
        #     test_2
        #     test_3
        #     teardown_module
        python -m pytest --log-cli-level=debug --color=yes --doctest-modules doc/livelog.py

        # demo test case assertion with early teardown with pytest -x
        python -m pytest -vv -x --log-cli-level=DEBUG --doctest-modules --color=yes doc/livelog_test_assertion.py

        # demo test case assertion with early teardown with pytest -x
        python -m pytest -vv -x --log-cli-level=DEBUG --doctest-modules --color=yes doc/livelog_bad_session.py
