name: DEV_DEMO
# Run dev.yml on phmutest develop branch

on:
  workflow_dispatch:


jobs:
  dev:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: tmarktaylor/phmutest
        ref: develop

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dev extra
      run: |
        python -m pip install --upgrade pip
        python -m pip install "."[dev]

    - name: Windows
      shell: cmd
      run: |
        call dev\ci.bat
        call dev\runcoverage.bat
      if: startswith(runner.os, 'Windows')
      continue-on-error: true

    - name: Linux/macOS
      run: |
        source dev/ci.sh
        source dev/runcoverage.sh
      if: startswith(runner.os, 'Linux') || startswith(runner.os, 'macOS')
      continue-on-error: true