name: DevEnv

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - master
  #     - main

jobs:
  deps:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      continue-on-error: true
      run: |
        python -m pip install --upgrade pip
        mkdir devreq
        pip install coverage
        pip install pytest
        pip install flake8
        pip install pep8-naming
        pip install mypy
        pip install typing
        pip install black
        pip install isort
        pip install mkdocs
        pip install tomli
        pip install Pygments
        pip install colorama
        #
        pip freeze
        pip freeze > devreq/requirements.txt

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: devreq
        path: devreq
        retention-days: 5
