name: DevEnv

on:
  workflow_dispatch:

jobs:
  deps:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      continue-on-error: true
      run: |
        python -m pip install --upgrade pip
        mkdir devreq
        mkdir wheels
        pip install "Click>=7.1.1"
        pip install "monotable>=2.1.1"
        # pip install "commonmark==0.8.1"
        pip install "commonmark>=0.9.1"
        pip install "recommonmark==0.5.0"
        pip install "sphinx<2"
        pip install "sphinx_rtd_theme<=0.5"
        pip install coverage
        pip install "pytest>=5"
        pip install flake8
        pip install pep8-naming
        pip install mypy
        pip install typing
        pip install check-manifest
        pip install twine
        pip install black
        #
        pip install setuptools
        pip install SecretStorage
        pip install jeepney
        pip install cffi
        pip install pycparser
        #
        pip freeze
        pip freeze > devreq/requirements.txt

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: devreq
        path: devreq
        retention-days: 5
