# Run this action if any of the install related files change.
# If a commit to one of these files breaks the install this action
# should fail.
# Let Travis CI handle events on the master branch.
name: Test pip install via setup.py

on:
  workflow_dispatch:
  #push:
  #  branches-ignore:
  #    - master
  #  paths:
  #    &install_paths
  #    - pyproject.toml
  #    - setup.cfg
  #    - setup.py
  #    - src/phmdoctest/main.py
  #pull_request:
  #  branches-ignore:
  #    - master
  #  paths:
  #    *install_paths

jobs:
  installtest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy-3.7", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: tmarktaylor/phmdoctest
          ref: master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-deps "."
          python -m pip install -r requirements.txt
          python -m pip install -r tests/requirements.txt
          pip freeze
      - name: Tests
        run: |
          pytest --strict -vv tests
          # invoke the installed script
          phmdoctest --help
