name: CI_README
# Run README.md examples on Python 3.7.

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/publish.yml'
      - '.github/workflows/wheel.yml'

jobs:
  # Create unittest and doctest testfiles from README.md and upload.
  # This job runs on Python > 3.7 since phmutest does not support Python 3.7.
  generate_testfiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: tmarktaylor/monotable
        ref: develop

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install phmutest
    - name: Generate testfiles
      run: |
        mkdir tmp
        phmutest README.md --generate tmp/readme_repl_examples.txt --replmode
    - name: Upload testfiles
      uses: actions/upload-artifact@v4
      with:
        name: readme-artifact
        path: tmp/*
        retention-days: 5

  # On Python 3.7, dowwnload and run the generated testfiles.
  run_testfiles:
    needs: generate_testfiles
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.7
    - uses: actions/download-artifact@v4
      with:
        name: readme-artifact
        path: testfiles
    - name: Show testfiles
      run: ls -l testfiles
    - name: Run testfiles
      run: |
        python -m doctest readme_repl_examples.txt
      working-directory: testfiles
