name: Selected pytests
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, pypy3]
    steps:
    - uses: actions/checkout@v2
      # todo- remove before running in phmdoctest repos
      with:
        repository: tmarktaylor/phmdoctest
        ref: master
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "pytest>=5"
        
    - name: Tests
      run: |
        pytest --strict -vv tests doc/test_setup_doctest.py
