name: Docs by tox

on:
  workflow_dispatch:

jobs:
  docs:
    # needs: tests
    runs-on: ubuntu-latest
    steps:
      - &mycheckout
        uses: actions/checkout@v2
        # todo- remove before running in phmdoctest repos
        with:
          repository: tmarktaylor/phmdoctest
          ref: pypy3issue
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          # This should be the same as in .readthedocs.yml  
          python-version: 3.7
      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Tox docs
        run: tox -e docs
          
      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          # in tox.ini this is {toxworkdir}/html
          path: .tox/docs/html
          retention-days: 5
