name: venv tests

on:
  workflow_dispatch:
  #push:
  #pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest]
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
      # todo- remove before running in phmdoctest repos
      with:
        repository: tmarktaylor/phmdoctest
        ref: develop

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Windows Venv
      run: |
        python -m venv ${{ github.workspace }}\env
        ${{ github.workspace }}\env\Scripts\activate.bat
      if: startswith(runner.os, 'Windows')
    - name: Linux/macOS Venv
      run: |
        python -m venv ${{ github.workspace }}/env
        source ${{ github.workspace }}/env/bin/activate
      if: startswith(runner.os, 'Linux') || startswith(runner.os, 'macOS')

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip --version
        python -m pip install --no-deps "."
        python -m pip install -r requirements.txt
        python -m pip install "pytest>=6"
    - name: Tests
      run: |
        # The next line creates the tmp subdirectory in tests.
        python -c "from pathlib import Path; d = Path('tests') / 'tmp'; d.mkdir()"
        phmdoctest project.md --report --outfile tests/tmp/test_project.py
        pytest --doctest-modules -vv tests
