name: Install from PYPI

on:
  workflow_dispatch:

env:
  project: phmdoctest
  version: 1.4.0

jobs:
  builddist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: PIP Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install "${{ ref.project }}==${{ ref.version }}"
        ${{ ref.project }} --version
